### ISSUE TITLE
ValueError in wait for logging for am_i_here

### ISSUE THREAD

**Issue by mshriver** [SatelliteQE/airgun#527]
```
 File "/home/jenkins/workspace/automation-6.8-tier2-rhel7/.env/lib64/python3.8/site-packages/airgun/entities/subscription.py", line 178, in post_navigate
    wait_for(
  File "/home/jenkins/workspace/automation-6.8-tier2-rhel7/.env/lib64/python3.8/site-packages/wait_for/__init__.py", line 170, in wait_for
    logger.debug("Started %(message)r at %(time)", {'message': message, 'time': st_time})
Message: '[SubscriptionListView]: Started %(message)r at %(time)'
Arguments: {'message': 'lambda defined as `lambda: self.am_i_here(*args, **kwargs),`', 'time': 28746020.587724153}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/jenkins/workspace/automation-6.8-tier2-rhel7/.env/lib64/python3.8/site-packages/_pytest/logging.py", line 74, in format
    return super().format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
```

Above exception is getting hit during tier testing of Robottelo in CI.

Don't have any investigation data at this time, but recording the issue.

**Comment by mshriver** [comment]
This will be fixed by an update to wait_for 1.1.3.

Requirements within airgun install the latest, but because airgun is installed via git through robottelo, robottelo is the limiting factor here.

Not an airgun bug.
Fixed through robottelo with: https://github.com/SatelliteQE/robottelo/pull/8076/files
